MODAT-166: Illegal base64 character 5f when decoding token with username with umlaut (Poppy)
https://folio-org.atlassian.net/browse/MODAT-166

Calling Token.getClaims(“x.eyJzdWIiOiJmb2_DpCJ9.x“) should return this JSON:

`{"sub":"fooä"}`

Actual result:

```
java.lang.IllegalArgumentException: Illegal base64 character 5f
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at org.folio.auth.authtokenmodule.tokens.Token.getClaims(Token.java:167)
```

Fix:

Replace
`new String(Base64.getDecoder().decode(encodedJson))`
with
`new String(Base64.getUrlDecoder().decode(encodedJson), UTF_8)`

(cherry picked from commit d447f14b891684942cfb7ee4256d61ef06107c5d)